sptint_3
Krisv1s/middle.messenger.praktikum.yandex pull request #3
Opened 2022-09-17 04:21 UTC by Krisv1s

2022-09-17 10:55 UTC, ivan-infro commented
Проверьте, что все изменения закоммичены и запушены. Сейчас во вкладке Files changed только одно изменение файла README

2022-09-17 11:07 UTC, Krisv1s commented
> Проверьте, что все изменения закоммичены и запушены. Сейчас во вкладке Files changed только одно изменение файла README

Исправил

2022-09-17 11:32 UTC, ivan-infro commented on README.md
> +<<<<<<< HEAD
Данные строки ("<<<<<<< HEAD", "=======", ">>>>>>> ee7440623601f08100b01cbdb09bacb7bcb1dfc2") добавляются при разрешении конфликтов слияния. В репозитории их быть не должно. IDE подсвечивают такие куски куда как интерактивные элементы (с возможностью принять "входящие" изменения, либо оставить "текущие")
<img width="855" alt="image" src="https://user-images.githubusercontent.com/5419627/190854470-bcd5cacd-3541-42b1-a114-2fcfa5f32a98.png">

2022-09-17 11:48 UTC, ivan-infro commented
Регулярное выражение, проверяющую валидность email, не пропускает корректный адрес: `mail@example.games`. Существует множество доменов первого уровня, длиннее 4 символов. Почитать про валидацию email подробнее можно тут: 
https://habr.com/ru/post/274985/
https://habr.com/ru/post/175375/

2022-09-17 11:50 UTC, ivan-infro commented
После авторизации и регистрации на странице отображается контент предыдущей страницы:
<img width="1367" alt="Screenshot 2022-09-17 at 13 49 20" src="https://user-images.githubusercontent.com/5419627/190855159-8ac015fd-6d17-4dd0-88b0-6cfe23006b87.png">
<img width="1366" alt="Screenshot 2022-09-17 at 13 49 49" src="https://user-images.githubusercontent.com/5419627/190855175-5a6d18b6-9c35-4b55-9b22-cb74212d519b.png">

2022-09-17 11:52 UTC, ivan-infro commented
На странице профиля не отображаются данные пользователя
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/5419627/190855215-41895b6d-623f-43c1-aac4-10fcb3b15b5f.png">

2022-09-17 11:55 UTC, Krisv1s commented
> На странице профиля не отображаются данные пользователя <img alt="image" width="1369" src="https://user-images.githubusercontent.com/5419627/190855215-41895b6d-623f-43c1-aac4-10fcb3b15b5f.png">

У меня все работает
![image](https://user-images.githubusercontent.com/51087951/190855343-8438d6a6-7a69-42c6-a716-eb1d43a77411.png)

2022-09-17 11:59 UTC, ivan-infro requested changes

2022-09-17 11:59 UTC, ivan-infro commented on src/utils/API/AuthAPI.ts
> +      headers: {
Все ручки используемого API принимают и отправляют данные в формате JSON, поэтому повторяющийся код можно вынести в базовый класс CoreAPI

2022-09-17 11:59 UTC, ivan-infro commented on src/utils/API/CoreAPI.ts
> +  public constructor(newUrl = 'https://ya-praktikum.tech/api/v2') {
Адрес API лучше вынести в отдельную константу

2022-09-17 11:59 UTC, ivan-infro commented on src/utils/Socket.ts
> +      const response = JSON.parse(res.data);
Если в JSON.parse попадет некорректная строка (например, в случае ошибки на сервере), то произойдет ошибка во время выполнения. Т.к. мы не можем доверять данным, пришедшим по сети, на 100%, лучше всегда оборачивать такие куски кода в try catch и обрабатывать возможные исключения.

2022-09-17 12:01 UTC, ivan-infro commented
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/5419627/190855561-156d8e6d-1c50-486a-a9b0-6c484329f7d7.png">

2022-09-17 12:02 UTC, ivan-infro commented
Проверьте, что приложение корректно реагирует на возвращаемые ошибки с сервера. Например, на ввод неправильного пароля:
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/5419627/190855634-75676adc-af9c-443b-8cfd-03607829b4f1.png">

2022-09-17 13:21 UTC, Krisv1s commented on src/utils/API/AuthAPI.ts
> +      headers: {
Не все, смена аватарки отправляет multipart/form-data;

2022-09-19 12:04 UTC, ivan-infro requested changes

2022-09-19 12:04 UTC, ivan-infro commented on src/pages/chats/chats.tmpl.ts
> +                            <button class="button button-profile-link">
В Firefox, при попытке навести на пункты меню, само меню тут же исчезает (как только "..." теряют hover)

2022-09-19 12:04 UTC, ivan-infro commented on src/pages/chats/chats.ts
> +      placeholder: 'ID пользователя',
Должно быть доступно добавление пользователей по логину (API /user/search)

2022-09-19 12:04 UTC, ivan-infro commented on src/pages/chats/chats.tmpl.ts
> +                    !=inputUserIdDelete
Используйте API GET /chats/{id}/users для отображения списка пользователей в чате

2022-09-19 12:06 UTC, ivan-infro requested changes

2022-09-19 12:06 UTC, ivan-infro commented on src/pages/singup/singup.ts
> +              this.props.msg = JSON.parse(res2.currentTarget.response).reason;
Ответ от сервера может быть не JSON'ом (например, если его вернул не наш backend, а прокси-сервер посередине). В таком случае здесь произойдет ошибка. Необходимо учитывать этот сценарий и использовать try catch

2022-09-20 16:29 UTC, merged